### PR TITLE
Update script to account for lack of hard zones

### PR DESCRIPTION
**Pull request by NunotabaS**
Not sure if all zones can be given 2400, but from playing these current MAX scores are the highest I could get.

### CODE REVIEW

**Comment by nathan78906** [comment]
Sorry about that, didn't see this in time, but you are correct, thanks!

**Comment by NunotabaS** [comment]
Would suggest that you update the loop at the bottom to allow Ctrl+C to stop the script. Otherwise this script must be `kill`-ed on unix machines to exit, which is annoying.

**Comment by nathan78906** [comment]
added, gave you credit in the commit message as well 👍

**Comment by NunotabaS** [comment]
Just had a quick look at your current version ... Seems like it would make 2x more requests than necessary in the worst case (only low difficulty) by spending two whole extra passes looking for the other difficulties.

This is probably fine but maybe consider doing a single pass instead...

**Comment by nathan78906** [comment]
Yup, I see that your previously submitted version would take care of that. Feel free to open another PR and i'll merge it.

**Pull request closed without merging**
